# Generated by Django 4.0.4 on 2023-09-25 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientID', models.PositiveIntegerField()),
                ('consultantID', models.PositiveIntegerField()),
                ('clientName', models.CharField(max_length=40, null=True)),
                ('consultantName', models.CharField(max_length=40, null=True)),
                ('category', models.CharField(choices=[('Dating', 'Dating'), ('Relationships', 'Relationships'), ('Breakups', 'Breakups'), ('Divorce', 'Divorce'), ('Marriage', 'Marriage'), ('Family', 'Family'), ('Business', 'Business')], max_length=100, null=True)),
                ('appointmentDate', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
                ('requestsnotes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
