# Generated by Django 4.2.5 on 2023-09-27 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dating_app', '0003_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='consultantName',
            new_name='adminName',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='appointmentDate',
            new_name='appointmentDateTime',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='requestsnotes',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='clientID',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='consultantID',
        ),
        migrations.AddField(
            model_name='appointment',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointment_admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointment',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointment_client', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
