# Generated by Django 4.0.4 on 2023-09-28 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating_app', '0004_rename_consultantname_appointment_adminname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='adminName',
        ),
        migrations.AddField(
            model_name='appointment',
            name='clientID',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
