# Generated by Django 4.0.4 on 2023-09-28 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating_app', '0005_remove_appointment_adminname_appointment_clientid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointmentDateTime',
            field=models.DateTimeField(),
        ),
    ]
