# Generated by Django 4.0.4 on 2023-09-29 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating_app', '0006_alter_appointment_appointmentdatetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
