# Generated by Django 4.0.4 on 2023-09-29 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating_app', '0007_message_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='senderID',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='senderName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointmentDateTime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
