# Generated by Django 4.2.5 on 2023-10-01 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dating_app', '0008_message_senderid_message_sendername_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='recipient',
        ),
    ]
