# Generated by Django 4.2.5 on 2023-10-03 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating_app', '0009_remove_message_recipient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
