# Generated by Django 4.0.4 on 2023-11-16 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import user_app.models
import user_app.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=20, null=True)),
                ('last_name', models.CharField(blank=True, max_length=20, null=True)),
                ('profile_pic', models.ImageField(blank=True, default='clear.png', upload_to=user_app.models.user_directory_path, validators=[user_app.validators.validate_file_size])),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('relationshipStatus', models.CharField(blank=True, choices=[('Never Married', 'Never Married'), ('Divorced', 'Dovorced'), ('Seperated', 'Seperated'), ('Widowed', 'Widowed'), ('Married', 'Married'), ('Seeking for Partner', 'Seeking for Partner')], max_length=20, null=True)),
                ('kidsStatus', models.CharField(blank=True, choices=[('No', 'No'), ('Yes', 'Yes'), ('Undecided', 'Undecided')], max_length=20, null=True)),
                ('hobbyList', models.CharField(blank=True, max_length=200, null=True)),
                ('profession', models.CharField(blank=True, max_length=200, null=True)),
                ('partnerPreference', models.CharField(blank=True, choices=[('No Preference', 'No Preference'), ('White/Caucasian', 'White/Caucasian'), ('Black/African', 'Black/African'), ('Asian', 'Asian'), ('Latin/Hispanic', 'Latin/Hispanic'), ('Indian', 'Indian'), ('Middle Eastern', 'Middle Eastern'), ('Native American', 'Native American'), ('Mixed', 'Mixed'), ('Other', 'Other')], max_length=20, null=True)),
                ('complexion', models.CharField(blank=True, choices=[('Dark', 'Dark'), ('Chocolate', 'Chocolate'), ('Fair', 'Fair'), ('White', 'White')], max_length=20, null=True)),
                ('seekingRelationship', models.CharField(blank=True, choices=[('Starting Family', 'Starting Family'), ('Marriage', 'Marriage'), ('Long Term', 'Long Term'), ('Short Term', 'Short Term'), ('Emotional Connection', 'Emotional Connection'), ('Companionship', 'Companionship'), ('Mentor', 'Mentor')], max_length=20, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('seeking', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('online_status', models.BooleanField(blank=True, default=False, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
