# Generated by Django 4.0.4 on 2023-10-10 13:53

from django.db import migrations, models
import user_app.models
import user_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_delete_appointment_remove_consultant_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='avatar.svg', upload_to=user_app.models.user_directory_path, validators=[user_app.validators.validate_file_size]),
        ),
    ]
