# Generated by Django 4.0.4 on 2023-10-11 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0006_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='complexion',
            field=models.CharField(blank=True, choices=[('Dark', 'Dark'), ('Chocolate', 'Chocolate'), ('Fair', 'Fair'), ('White', 'White')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='dateOfBirth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='hobbyList',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='kidsStatus',
            field=models.CharField(blank=True, choices=[('No', 'No'), ('Yes', 'Yes'), ('Undecided', 'Undecided')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='partnerPreference',
            field=models.CharField(blank=True, choices=[('No Preference', 'No Preference'), ('White/Caucasian', 'White/Caucasian'), ('Black/African', 'Black/African'), ('Asian', 'Asian'), ('Latin/Hispanic', 'Latin/Hispanic'), ('Indian', 'Indian'), ('Middle Eastern', 'Middle Eastern'), ('Native American', 'Native American'), ('Mixed', 'Mixed'), ('Other', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='relationshipStatus',
            field=models.CharField(blank=True, choices=[('Never Married', 'Never Married'), ('Divorced', 'Dovorced'), ('Seperated', 'Seperated'), ('Widowed', 'Widowed'), ('Married', 'Married'), ('Seeking for Partner', 'Seeking for Partner')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='seekingRelationship',
            field=models.CharField(blank=True, choices=[('Starting Family', 'Starting Family'), ('Marriage', 'Marriage'), ('Long Term', 'Long Term'), ('Short Term', 'Short Term'), ('Emotional Connection', 'Emotional Connection'), ('Companionship', 'Companionship'), ('Mentor', 'Mentor')], max_length=20, null=True),
        ),
    ]
