# Generated by Django 4.0.4 on 2023-10-30 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0008_profile_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profileCover',
        ),
    ]
