# Generated by Django 4.0.4 on 2023-10-31 18:52

from django.db import migrations, models
import user_app.models
import user_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0009_remove_profile_profilecover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='clear.png', upload_to=user_app.models.user_directory_path, validators=[user_app.validators.validate_file_size]),
        ),
    ]
