# Generated by Django 4.0.4 on 2023-11-01 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0010_remove_profile_first_name_remove_profile_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='dateOfBirth',
        ),
    ]
